/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//enablamo clock za gpiod
	SET_BIT(RCC->AHB1ENR, RCC_AHB1ENR_GPIODEN);

	//nastavimo v alternate function mode
	SET_BIT(GPIOD->MODER, GPIO_MODER_MODER12_1);
	CLEAR_BIT(GPIOD->MODER, GPIO_MODER_MODER13_0);
	SET_BIT(GPIOD->MODER, GPIO_MODER_MODER13_1);
	CLEAR_BIT(GPIOD->MODER, GPIO_MODER_MODER14_0);
	SET_BIT(GPIOD->MODER, GPIO_MODER_MODER14_1);
	CLEAR_BIT(GPIOD->MODER, GPIO_MODER_MODER15_0);
	SET_BIT(GPIOD->MODER, GPIO_MODER_MODER15_1);

	//enablamo clock za tim4
	SET_BIT(RCC->APB1ENR, RCC_APB1ENR_TIM4EN);
	//prescaler
	WRITE_REG(TIM4->PSC, 7999 );
	//auto reaload value
	WRITE_REG(TIM4->ARR, 9999 );
	//update interrupt enable
	WRITE_REG(TIM4->DIER,TIM_DIER_UIE);

	//nastavimo vrednosti za primerjavo registrom
	WRITE_REG(TIM4->CCR1, 2000);
	WRITE_REG(TIM4->CCR2, 4000);
	WRITE_REG(TIM4->CCR3, 6000);
	WRITE_REG(TIM4->CCR4, 8000);

	//povezemo pd12-15 na tim4 kanal
	//
	SET_BIT(GPIOD->AFR[1],0x22220000);

	//pocistimo ccmr registre da dobimo output compare mode
	CLEAR_BIT(TIM4->CCMR1, TIM_CCMR1_CC1S_0);
	CLEAR_BIT(TIM4->CCMR1, TIM_CCMR1_CC1S_1);
	CLEAR_BIT(TIM4->CCMR1, TIM_CCMR1_CC2S_0);
	CLEAR_BIT(TIM4->CCMR1, TIM_CCMR1_CC2S_1);

	//nastavimo na pwm mode 2
	SET_BIT(TIM4->CCMR1, TIM_CCMR1_OC1M_0 );
	SET_BIT(TIM4->CCMR1, TIM_CCMR1_OC1M_1 );
	SET_BIT(TIM4->CCMR1, TIM_CCMR1_OC1M_2 );

	SET_BIT(TIM4->CCMR1, TIM_CCMR1_OC2M_0 );
	SET_BIT(TIM4->CCMR1, TIM_CCMR1_OC2M_1 );
	SET_BIT(TIM4->CCMR1, TIM_CCMR1_OC2M_2 );

	SET_BIT(TIM4->CCMR2, TIM_CCMR2_OC3M_0);
	SET_BIT(TIM4->CCMR2, TIM_CCMR2_OC3M_1);
	SET_BIT(TIM4->CCMR2, TIM_CCMR2_OC3M_2);

	SET_BIT(TIM4->CCMR2, TIM_CCMR2_OC4M_0);
	SET_BIT(TIM4->CCMR2, TIM_CCMR2_OC4M_1);
	SET_BIT(TIM4->CCMR2, TIM_CCMR2_OC4M_2);

	//enablamo output kanale 1-4 od tim4
	SET_BIT(TIM4->CCER,TIM_CCER_CC1E);
	SET_BIT(TIM4->CCER,TIM_CCER_CC2E);
	SET_BIT(TIM4->CCER,TIM_CCER_CC3E);
	SET_BIT(TIM4->CCER,TIM_CCER_CC4E);
	//zacnemo timer
	SET_BIT(TIM4->CR1,TIM_CR1_CEN);


    /* Loop forever */
	for(;;);
}





